# Generated by Django 5.2.8 on 2025-12-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recrutement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidature",
            name="nom",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="candidature",
            name="prenom",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
    ]
