# Generated by Django 6.0 on 2025-12-31 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_alter_event_club'),
        ('recrutement', '0002_candidature_nom_candidature_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
    ]
