# Generated by Django 6.0 on 2025-12-31 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_alter_event_club'),
        ('recrutement', '0003_alter_annonce_club_alter_candidature_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.event'),
        ),
    ]
