# Generated by Django 6.0 on 2025-12-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='cne',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNE (Code Massar)'),
        ),
        migrations.AddField(
            model_name='profil',
            name='filiere',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Filière'),
        ),
    ]
