# Generated by Django 6.0 on 2026-01-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_profil_cne_profil_filiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='cne',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CNE (Code Massar)'),
        ),
    ]
