# Generated by Django 5.2.8 on 2025-12-10 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cellule",
            name="membres",
            field=models.ManyToManyField(
                blank=True, related_name="membres_cellule", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="membres",
            field=models.ManyToManyField(
                blank=True, related_name="membres_club", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
