# Generated by Django 5.2.8 on 2025-12-10 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0002_cellule_membres_club_membres"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cellule",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cellule",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cellules",
                to="clubs.event",
            ),
        ),
        migrations.AlterField(
            model_name="cellule",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cellules",
                to="clubs.club",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cellule",
            unique_together={("nom", "club", "event")},
        ),
    ]
