# Generated by Django 5.2.8 on 2025-12-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0003_alter_cellule_unique_together_cellule_event_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="clubs/"),
        ),
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="events/"),
        ),
    ]
