# Generated by Django 5.2.8 on 2025-12-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0004_club_image_event_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="chefs",
        ),
    ]
