# Generated by Django 5.2.8 on 2025-12-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0005_remove_event_chefs"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="coordinateur",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
