# Generated by Django 5.2.8 on 2025-12-12 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0006_club_coordinateur"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="chefs",
            field=models.ManyToManyField(
                blank=True, related_name="events_chefs", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
