# Generated by Django 5.2.8 on 2025-12-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0007_event_chefs"),
    ]

    operations = [
        migrations.AddField(
            model_name="cellule",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
