# Generated by Django 6.0 on 2026-01-09 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_alter_event_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Budget Alloué (DH)'),
        ),
        migrations.AddField(
            model_name='event',
            name='note_admin',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Note Admin (/20)'),
        ),
    ]
